function [ CC ] = love2CC( A,C,F,L,N )
%[ CC ] = love2CC( A,C,F,L,N )
% construct 6x6 elastic tensor from Love parameters
    CC= [ A      A-2.*N F  0  0  0  ; ...
         A-2.*N A      F  0  0  0  ; ...
         F      F      C  0  0  0  ; ...
         0      0      0  L  0  0  ; ...
         0      0      0  0  L  0  ; ...
         0      0      0  0  0  N ] ;

end

